### PR TITLE
Support php7 + composer update

### PR DESCRIPTION
**Pull request by sd-lueckel**
- Added PHP7 to travis
- run a composer update cause .lock file was not updated and a composer install tells that php7 is not supported

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The lock file should not be committed.

**Comment by GrahamCampbell** [comment]
Also, no pull requests will be accepted to this repo, as per the readme.

**Comment by sd-lueckel** [comment]
Then the .lock file should be removed and inserted to .gitignore

**Comment by GrahamCampbell** [comment]
> Is there a special reason why the composer.lock should not be committed?

Yeh. The purpose of the lock file is to lock the dependencies into a known state for deployment of applications. Since this is a library, it makes no sense to do this, in most circumstances.

**Comment by vimishor** [comment]
> Then the .lock file should be removed and inserted to .gitignore!

It is in develop branch.

The lock file was committed initially because I didn't know if all vendors will respect semver or not.

**Comment by GrahamCampbell** [comment]
>The lock file was committed initially because I didn't know if all vendors will respect semver or not.

The lock file does nothing to protect you against that. The lock file is not inherited when this package is installed somewhere.

**Comment by vimishor** [comment]
@GrahamCampbell In a library case, the lock file helps the developer, not the consumer(s) and since the lock file from a library doesn't affect the consumer, it is harmless if you committed it or not.

Personally I (_ab_)use the lock file inside a library to pinpoint more easily the vendors which don't respect the semver: _Consumer explodes, but library's tests are green._

Not a silver bullet, but it worked in the last years.

**Pull request closed without merging**
